-- Native Credits tariff. Integer micro-Credits per million tokens (1 Credit = 1000000).
-- Preserves the visible Credits prices at the native billing migration; no runtime exchange rate.
BEGIN IMMEDIATE;
INSERT INTO model_prices (id,protocol,public_model,input_microcredits_per_1m,input_cache_hit_microcredits_per_1m,output_microcredits_per_1m,unit,billing,created_at,updated_at)
VALUES ('price_babelark_gpt-6-luna','openai','gpt-6-luna',70000000, 7000000, 350000000, 'CREDITS','{"mode":"tokens","token_tiers":[{"above_input_tokens":272000,"input_microcredits_per_1m_tokens":"140000000","input_cache_hit_microcredits_per_1m_tokens":"14000000","output_microcredits_per_1m_tokens":"525000000"}]}',strftime('%Y-%m-%dT%H:%M:%SZ','now'),strftime('%Y-%m-%dT%H:%M:%SZ','now'))
ON CONFLICT(protocol,public_model) DO UPDATE SET input_microcredits_per_1m=excluded.input_microcredits_per_1m,input_cache_hit_microcredits_per_1m=excluded.input_cache_hit_microcredits_per_1m,output_microcredits_per_1m=excluded.output_microcredits_per_1m,unit=excluded.unit,billing=excluded.billing,updated_at=excluded.updated_at;
INSERT INTO model_prices (id,protocol,public_model,input_microcredits_per_1m,input_cache_hit_microcredits_per_1m,output_microcredits_per_1m,unit,billing,created_at,updated_at)
VALUES ('price_babelark_gpt-6-sol','openai','gpt-6-sol',1400000000, 140000000, 7000000000, 'CREDITS','{"mode":"tokens","token_tiers":[{"above_input_tokens":272000,"input_microcredits_per_1m_tokens":"2800000000","input_cache_hit_microcredits_per_1m_tokens":"280000000","output_microcredits_per_1m_tokens":"10500000000"}]}',strftime('%Y-%m-%dT%H:%M:%SZ','now'),strftime('%Y-%m-%dT%H:%M:%SZ','now'))
ON CONFLICT(protocol,public_model) DO UPDATE SET input_microcredits_per_1m=excluded.input_microcredits_per_1m,input_cache_hit_microcredits_per_1m=excluded.input_cache_hit_microcredits_per_1m,output_microcredits_per_1m=excluded.output_microcredits_per_1m,unit=excluded.unit,billing=excluded.billing,updated_at=excluded.updated_at;
COMMIT;
